import type { Component } from './types';

/**
 * 987 (2005–2012 Boxster/Cayman) component hotspots for the Component Explorer's
 * 2D cutaways. `view: 'front'` pins sit on the whole-car cutaway
 * (/assets/cutaway-987.jpg); `view: 'rear'` pins sit on the flat-six + transaxle
 * engine cutaway (/assets/engine-987.jpg). Same `Component` shape as the 981 set.
 *
 * Notes reflect both eras where they differ: 987.1 (2005–2008, M96/M97, hydraulic
 * steering, port injection, Tiptronic) vs 987.2 (2009–2012, 9A1 DFI, PDK). The
 * engine cutaway image is a 987.2 9A1 with PDK + factory exhaust.
 * `ix/iy` are percentages tuned against the two images.
 */
export const COMPONENTS_987: Component[] = [
  // ───────────────────────── FRONT · whole-car cutaway ─────────────────────────
  { id: 'cooling-front', label: 'Front Radiators & Condenser', sub: 'Cooling · front bumper', system: 'Cooling', diff: 2, time: '~40 min',
    part: 'Twin radiators + A/C condenser (L/R)', spec: 'G40-class coolant · engine-mounted expansion tank', interval: 'Coolant 4 yr · inspect yearly', torque: 'Hose clamp 4 Nm',
    notes: 'Twin radiators and the A/C condenser sit low behind the front bumper. They pack with leaves and road debris — the classic 987 corrosion spot. Clear the drains and check the fins every spring.',
    steps: ['Lift front, remove underbody tray', 'Blow out fins, clear debris & drains', 'Inspect lower corners for rot/leaks', 'Pressure-test system to ~1.5 bar', 'Refit tray'],
    view: 'front', ix: 12, iy: 52 },
  { id: 'battery', label: '12V Battery', sub: 'Electrical · front trunk', system: 'Electrical', diff: 1, time: '~20 min',
    part: 'Group-48 / H6 AGM 12 V', spec: 'Under the front luggage-compartment floor', interval: 'Replace 4–6 yr', torque: 'Terminal clamp 6 Nm',
    notes: 'Battery lives under the frunk floor panel. Use a memory-saver before disconnect. Negative off first, positive on first; re-register if switching to AGM.',
    steps: ['Open frunk, lift floor panel', 'Connect memory saver to OBD', 'Disconnect negative then positive', 'Swap battery, refit clamps to 6 Nm', 'Re-register battery type if needed'],
    view: 'front', ix: 16, iy: 40 },
  { id: 'fbrakes', label: 'Front Brakes', sub: 'Pads · discs · fluid', system: 'Brakes', diff: 3, time: '~90 min',
    part: 'Pads + discs (S: 318 mm · base: 298 mm)', spec: '4-piston fixed monobloc caliper (S)', interval: 'Inspect yearly · fluid 2 yr', torque: 'Wheel bolts 130 Nm · caliper 85 Nm',
    notes: 'Front-left wear sensor. Lube guide/anti-rattle hardware and bed pads in over ~200 miles. Cayman S / Boxster S run the larger 318 mm rotor.',
    steps: ['Loosen wheel bolts, lift & support', 'Remove wheel, retaining clip & pins', 'Lever pistons back, fit new pads', 'Reset wear sensor if triggered', 'Torque wheel bolts to 130 Nm in star'],
    view: 'front', ix: 19, iy: 69 },
  { id: 'steering', label: 'Hydraulic Power Steering', sub: 'Rack · pump · PS fluid', system: 'Steering', diff: 3, time: '~45 min',
    part: 'Hydraulic rack · PS fluid Pentosin CHF 11S', spec: 'Belt-driven pump + front reservoir (NOT electric)', interval: 'Check fluid & boots yearly', torque: 'Track rod end 100 Nm',
    notes: 'Unlike the later 981 (electric), the 987 uses HYDRAULIC power steering with a pump, reservoir and CHF 11S fluid. Watch for weeping lines, a whining pump (low fluid) and split rack boots.',
    steps: ['Check PS reservoir level cold', 'Inspect lines & rack boots for leaks', 'Listen for pump whine on lock', 'Top up with CHF 11S only', 'Alignment after any track-rod work'],
    view: 'front', ix: 27, iy: 56 },
  { id: 'fsuspension', label: 'Front Suspension', sub: 'MacPherson struts · arms', system: 'Suspension', diff: 4, time: 'shop',
    part: 'Struts · control arms · drop links', spec: 'MacPherson front · PASM optional', interval: 'Inspect yearly / after track', torque: 'Strut top 80 Nm · arm bolts 90 Nm + 90°',
    notes: 'Clunks over bumps are usually drop-links or tired control-arm bushings. Check ball-joint and tie-rod play; four-wheel alignment after any arm or strut work.',
    steps: ['Road-test for clunk / pull', 'Inspect boots, drop-links, bushings', 'Check ball-joint & tie-rod play', 'Replace worn links in pairs', 'Four-wheel alignment after'],
    view: 'front', ix: 23, iy: 62 },
  { id: 'cabinfilter', label: 'Cabin / Pollen Filter', sub: 'HVAC intake', system: 'HVAC', diff: 1, time: '~15 min',
    part: 'Activated-carbon pollen element', spec: 'Behind the front-compartment firewall trim', interval: 'Yearly / at each minor service', torque: 'n/a — clip-in',
    notes: 'A clogged pollen filter is the #1 cause of weak airflow and musty A/C on a 987. Replaced at every minor service on the factory schedule.',
    steps: ['Open frunk, remove firewall trim', 'Release filter cover clips', 'Slide out old element (note airflow arrow)', 'Vacuum the housing', 'Fit new filter, refit cover'],
    view: 'front', ix: 32, iy: 43 },
  { id: 'fuel', label: 'Fuel Tank & Pump', sub: 'In-tank pump · sender', system: 'Fuel', diff: 3, time: '~90 min',
    part: 'In-tank pump/sender module', spec: '~64 L central tank · 987.1 port / 987.2 DFI', interval: 'Inspect — filter is lifetime', torque: 'Pump flange ring 60 Nm',
    notes: 'The fuel tank sits centrally, ahead of the engine. The filter is integrated in the in-tank pump module. On DFI (987.2) relieve high-pressure rail pressure before opening any union.',
    steps: ['Relieve fuel pressure (pull pump fuse, run dry)', 'Access pump under cabin/tank cover', 'Disconnect quick-connects carefully', 'Replace module, fit new seal ring', 'Prime and leak-check'],
    view: 'front', ix: 47, iy: 50 },
  { id: 'engine', label: 'Flat-Six Engine', sub: 'Mid-mounted · see ENGINE tab', system: 'Engine', diff: 3, time: 'varies',
    part: '987.1 M96/M97 · 987.2 9A1 (2.7/2.9/3.4)', spec: 'Mid-mounted boxer-six behind the cabin', interval: 'Oil yearly / 10k mi', torque: 'See ENGINE tab per component',
    notes: 'The boxer-six sits amidships, ahead of the transaxle. Switch to the ENGINE tab for oil, plugs, intake, throttle and coolant service points. 987.1 M96/M97 differ from the 987.2 9A1 DFI shown in the engine cutaway.',
    steps: ['Open the rear engine lid for access', 'Use the ENGINE tab for per-part service', 'Check for oil/coolant weeps at the case', 'Note the flat-six firing order (see cylinder ref)', 'Keep the engine-bay drains clear'],
    view: 'front', ix: 66, iy: 31 },
  { id: 'rbrakes', label: 'Rear Brakes', sub: 'Pads · discs · park brake', system: 'Brakes', diff: 3, time: '~80 min',
    part: 'Pads + discs (S: 299 mm)', spec: 'Fixed caliper · drum-in-hat parking brake', interval: 'Inspect yearly', torque: 'Wheel bolts 130 Nm · caliper 85 Nm',
    notes: 'Separate drum-in-hat parking brake inside the rear rotor. Release the park brake fully and retract pistons squarely before fitting new pads.',
    steps: ['Loosen bolts, lift & support rear', 'Release park brake, remove caliper', 'Fit new pads, lube hardware', 'Seat caliper, torque 85 Nm', 'Wheel bolts 130 Nm in star'],
    view: 'front', ix: 80, iy: 69 },
  { id: 'exhaust', label: 'Exhaust & Tailpipes', sub: 'Rear mufflers · PSE', system: 'Exhaust', diff: 3, time: '~90 min',
    part: 'Rear silencers · optional Sport Exhaust (PSE)', spec: 'Twin rear mufflers · dual tips', interval: 'Inspect yearly', torque: 'Clamp nut 23 Nm · hanger 23 Nm',
    notes: 'Check for blowing gaskets at the cat/silencer joints and perished rubber hangers. If the optional PSE is fitted, a sticky sound-valve is usually a perished vacuum line.',
    steps: ['Inspect from cats rearward for leaks', 'Check hangers & heat shields', 'Test PSE valve open/close (if fitted)', 'Replace gaskets at flanges', 'Clamp nuts to 23 Nm'],
    view: 'front', ix: 88, iy: 55 },
  { id: 'wheels', label: 'Wheels & Tyres', sub: 'Rims · tyres · TPMS', system: 'Wheels', diff: 1, time: '~30 min',
    part: 'Staggered 18"/19" · N-rated tyres', spec: 'Square/staggered per spec · N-spec recommended', interval: 'Check pressures · rotate as specified', torque: 'Wheel bolts 130 Nm',
    notes: 'Run N-spec tyres for correct handling. Check cold pressures to the door/fuel-flap placard and inspect the inner edge for camber wear.',
    steps: ['Check cold pressures to placard', 'Inspect tread depth & inner edge', 'Reset TPMS after changes (987.2)', 'Torque bolts to 130 Nm in star', 'Re-torque after ~50 miles'],
    view: 'front', ix: 30, iy: 80 },

  // ───────────────────────── ENGINE · flat-six + transaxle cutaway ─────────────────────────
  { id: 'oil', label: 'Engine Oil & Filter', sub: 'Lubrication · flat-six', system: 'Engine', diff: 1, time: '~45 min',
    part: '987.1 Mahle OX254D4 · 987.2 cartridge · 0W-40', spec: '~8.3 L w/ filter (3.4) · Mobil 1 0W-40 (A40)', interval: 'Yearly / 10k mi', torque: 'Drain plug ~37 Nm · cap 25 Nm',
    notes: 'Drain from below via the sump plug; the filter is on top under the rear lid. 987.1 (M96/M97) uses the Mahle OX254D4 cartridge; the 987.2 9A1 uses its own cartridge. New crush washer every time.',
    steps: ['Warm engine, lift & level the car', 'Remove underbody panel, drain sump', 'New crush washer, drain plug to spec', 'Swap cartridge under the top cap (25 Nm)', 'Refill 0W-40, verify level', 'Reset oil-service interval'],
    view: 'rear', ix: 62, iy: 22 },
  { id: 'intake', label: 'Intake Manifold & Plenum', sub: 'Induction', system: 'Engine', diff: 2, time: '~60 min',
    part: 'Intake manifold / resonance flaps', spec: '987.2 9A1 variable resonance intake', interval: 'Inspect · clean with throttle', torque: 'Manifold bolts 9 Nm',
    notes: 'The plenum sits on top of the engine. On the 9A1 the resonance-flap intake can throw a fault if a flap actuator sticks — check before condemning sensors.',
    steps: ['Open rear lid, remove covers', 'Inspect manifold for cracks/leaks', 'Check resonance-flap actuator (987.2)', 'Reseal joints as needed', 'Bolts to 9 Nm'],
    view: 'rear', ix: 34, iy: 24 },
  { id: 'airfilter', label: 'Air Filter', sub: 'Engine induction', system: 'Engine', diff: 1, time: '~20 min',
    part: 'Panel air-filter element', spec: 'Single panel element in the airbox', interval: 'At major service / yearly if tracked', torque: 'Airbox screws 4 Nm',
    notes: 'The airbox is on the engine-bay side. Quick breathing win; pairs nicely with a throttle-body clean.',
    steps: ['Open rear engine lid', 'Release airbox lid clips/screws', 'Lift out the panel filter', 'Wipe the housing clean', 'Fit new element, reseat lid'],
    view: 'rear', ix: 13, iy: 56 },
  { id: 'throttle', label: 'Throttle Body', sub: 'Drive-by-wire', system: 'Engine', diff: 2, time: '~40 min',
    part: 'Electronic throttle body + cleaner', spec: 'Adaptation required after cleaning', interval: 'Clean if idle rough', torque: 'TB bolts 9 Nm',
    notes: 'Carbon on the butterfly causes an unstable idle. Clean with a TB-safe cleaner and run a throttle adaptation with a scan tool afterward; do not force the flap.',
    steps: ['Remove the intake tube to the TB', 'Clean butterfly & bore (TB-safe cleaner)', 'Do not force the flap open', 'Refit tube, clear adaptations', 'Idle-learn with a scan tool'],
    view: 'rear', ix: 47, iy: 41 },
  { id: 'coolant', label: 'Coolant Expansion Tank', sub: 'Cooling reservoir', system: 'Cooling', diff: 1, time: '~15 min',
    part: 'Expansion tank + cap', spec: 'G40-class coolant · cold level at mark', interval: 'Cap & level yearly', torque: 'n/a',
    notes: 'The engine-bay expansion tank has the fill cap and level marks (the blue/white caps in the cutaway). A weak cap causes slow pressure loss; check cold, never open hot.',
    steps: ['Check level cold at the seam mark', 'Inspect cap seal for cracks', 'Top up with the correct coolant only', 'Squeeze hoses for brittleness', 'Bleed if air was introduced'],
    view: 'rear', ix: 45, iy: 12 },
  { id: 'plugs', label: 'Spark Plugs & Coils', sub: 'Ignition · flat-six', system: 'Engine', diff: 3, time: '~2 hr',
    part: '6× spark plugs + coil packs', spec: '6-cylinder · gap per spec', interval: '987.1 36k/4 yr · 987.2 40k/4 yr', torque: 'Plug 30 Nm · coil bolt 9 Nm',
    notes: 'Access is tight down the engine-bay sides. Label cylinders (see the CYLINDER NUMBERING reference), anti-seize lightly and do not over-torque the alloy heads.',
    steps: ['Remove rear lid & intake covers', 'Unbolt coil packs (9 Nm), label cylinders', 'Remove plugs with a thin-wall socket', 'Gap-check & fit new plugs to 30 Nm', 'Refit coils, clear adaptation'],
    view: 'rear', ix: 27, iy: 35 },
  { id: 'trans', label: 'Transaxle (PDK / Manual / Tiptronic)', sub: 'Rear-mounted gearbox', system: 'Transmission', diff: 4, time: '~2.5 hr',
    part: '987.2 PDK · 987.1 Tiptronic S / 6-spd manual', spec: 'PDK/Tiptronic ATF · manual 75W-90 gear oil', interval: 'Manual/PDK oil ~120k · Tiptronic ATF+filter', torque: 'Drain/fill 45 Nm',
    notes: 'The transaxle bolts to the back of the engine (silver unit in the cutaway). Earlier-than-factory ATF/gear-oil changes are cheap insurance. Tiptronic also gets an ATF filter.',
    steps: ['Lift & level, warm to temperature', 'Drain the transaxle, measure quantity', 'Replace filter/clean magnet (auto)', 'Refill the exact amount via the fill port', 'Fill plug to 45 Nm, road-test shifts'],
    view: 'rear', ix: 63, iy: 55 },
  { id: 'exhausteng', label: 'Manifolds, Cats & Silencers', sub: 'Exhaust · engine-out view', system: 'Exhaust', diff: 3, time: '~2 hr',
    part: 'Headers · catalytic converters · rear silencers', spec: 'Twin-bank manifolds → cats → mufflers', interval: 'Inspect yearly', torque: 'Manifold nuts 23 Nm',
    notes: 'The full system is visible engine-out here: manifolds off each bank into the cats, then the twin rear silencers. Check for cracked manifolds (a known flat-six weak point) and blowing gaskets.',
    steps: ['Inspect manifolds for cracks/leaks', 'Check cat heat shields & O2 sensors', 'Inspect silencer joints & hangers', 'Replace gaskets at flanges', 'Nuts to 23 Nm'],
    view: 'rear', ix: 82, iy: 52 },
];
